### ISSUE TITLE
Issue with installation requirements

### ISSUE THREAD

**Issue by paradox42** [genshin-kit/genshin-kit#10]
Find that typescript must be installed in order to use the package correctly. 

Otherwise when trying to import this package it will through an MODULE_NOT_FOUND error, states that there is no #index.js# file under "node_modules/genshin-kit/src/lib/index.js", even with package.json the "main: lib/index.js" is specified.

Ran into this error while installation, installing typescript solved it for me

**Comment by Dragon-Fish** [comment]
That's strange, I can't reproduce this bug in my JS project that doesn't contain TS as a dependency.

Can you provide some console trace?

**Comment by Dragon-Fish** [comment]
The `index.js` file should under `node_modules/genshin-kit/lib/index.js`

**Comment by paradox42** [comment]
> That's strange, I can't reproduce this bug in my JS project that doesn't contain TS as a dependency.
> 
> Can you provide some console trace?

Its okay this is not even an issue, I made an issue to be a reminder to whom might ran into the same problem I did.

You mentioned you JS project that doesn't contain TS as a dependency, in my case I installed TS globally to solve the problem, probably you also have TS installed globally so the project used it to compile.

**Comment by Dragon-Fish** [comment]
If you have other problems, welcome to open issues (\*^▽^\*)
