### ISSUE TITLE
增加风来人活动查询

### ISSUE THREAD

**Issue by thezion** [genshin-kit/genshin-kit#11]
因为风来人是原神的顶级副本。。

**Comment by Dragon-Fish** [comment]
我还以为是 PR，结果是 issue（悲

这种查询我暂时没有需求所以一时半会儿应该是不会做的，如果你知道接口的话其实可以用文档里未注明的 `request` 方法发起请求。

**Comment by Dragon-Fish** [comment]
似乎可以实现，先重开
