### ISSUE TITLE
[BUG?] 关于xxx的故障/The bug is about getting userinfo

### ISSUE THREAD

**Issue by Sureiyaaa** [genshin-kit/genshin-kit#27]
I was trying to get the user info again I don't know if this is a bug or what but it says "Data is not public for this user"
Even though it is public on my account

Code:
console.log(this.client.genshin.getUserInfo(800151827).then(console.log, console.error))

Error:
{ code: 10102, message: 'Data is not public for the user' }

- genshin-kit: 2.4.1
- Node.js: 16

**Comment by Sureiyaaa** [comment]
I tried to use my hoyolab account ID instead but it says a different error now
Code:
console.log(this.client.genshin.getUserInfo(10275214).then(console.log, console.error))
Error:
{ code: 1009, message: '角色信息错误' }
I don't know what it means but I think it says "Role information error"

**Comment by AlPha5130** [comment]
Did you use your hoyolab account cookies to login? `loginWithCookie`

**Comment by Dragon-Fish** [comment]
> I tried to use my hoyolab account ID instead but it says a different error now

P.S. This error was expected. You should use the in-game UID to query.

**Comment by Sureiyaaa** [comment]
I tried the in game uid but still it says not public

**Comment by Sureiyaaa** [comment]
> Did you use your hoyolab account cookies to login? `loginWithCookie`

I did

**Comment by Dragon-Fish** [comment]
Why did he get a Chinese error message. Maybe forgot `setServerType`?

**Comment by Sureiyaaa** [comment]
I did set my setServerType and Locale

client.genshin.setServerType('os');
client.genshin.setServerLocale('en-us');

**Comment by Sureiyaaa** [comment]
```
GenshinKit {
  _cache: {},
  cookie: 'ltoken=***; ltuid=***',
  _getApiEndpoint: [Function: _getApiEndpoint],
  _getDS: [Function: _getDS],
  _getHttpHeaders: [Function: _getHttpHeaders],
  _getServer: [Function: _getServer],
  _hoyolabVersion: [Function: _hoyolabVersion],
  request: [AsyncFunction: request],
  serverType: 'os',
  serverLocale: 'en-us',
  getCharacters: [AsyncFunction: getAllCharacters],
  getUserRoles: [AsyncFunction: getAllCharacters],
  getAbyss: [AsyncFunction: getSpiralAbyss],
  getCurAbyss: [AsyncFunction: getCurrentAbyss],
  getPrevAbyss: [AsyncFunction: getPreviousAbyss],
  setCookie: [Function: loginWithCookie]
}
```

**Comment by AlPha5130** [comment]
It worked on my side, so I don't know where it goes wrong

**Comment by AlPha5130** [comment]
But I can't query your info, so it should be your settings

**Comment by Sureiyaaa** [comment]
I got a new error tho
```
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

**Comment by Sureiyaaa** [comment]
is it my node.js version?

**Comment by AlPha5130** [comment]
I don't think it's node.js version

**Comment by Sureiyaaa** [comment]
Oh you mean its in my account?

**Comment by AlPha5130** [comment]
> But I can't query your info, so it should be your settings
Since I can query myself, it should be so

**Comment by Sureiyaaa** [comment]
Actually it was wrong on my part Thank you!
