### ISSUE TITLE
Missing characters, data required

### ISSUE THREAD

**Issue by tawan475** [genshin-kit/genshin-kit#34]
## 简述此故障/Describe the bug

Read Title
-

## 如何重现此故障/To Reproduce

Install Genshin-Kit
run `new util.CharacterNickname().getNicknamesById(10000002);`

# THE 10000002 CHARACTER IS MISSING
Go in `./node_modules/genshin-kit/lib/util/CharacterNickname.js` Line: `28`
There is suppose to be 10000002 (Ayaka) present, but not.

The temporary fix is to just add back in
```
  {
    id: 10000002,
    nicknames: [
      '神里绫华',
      'kamisatoayaka',
      'shenlilinghua',
      '白鹭霜华',
      '绫华',
      'ayaka',
    ],
   },
  ```
Please update in main release

## 本应出现的情况/Expected behavior

Return array of nicknames for 10000002

## 环境信息/Your environment

- genshin-kit: latest
- Node.js: v14.5.0
- 系统/OS: Windows

**Comment by Dragon-Fish** [comment]
Hi, what is your exact version of genshin-kit.

**Comment by tawan475** [comment]
2.4.1

**Comment by tawan475** [comment]
Also kazuha is missing (10000047)

**Comment by AlPha5130** [comment]
You may want to use 2.4.2, this has been added.

**Comment by AlPha5130** [comment]
For 10000047 you can make an pr

**Comment by tawan475** [comment]
ive added kazuha in this pull request #35

**Comment by tawan475** [comment]
there are still some missing characters
eula and traveller - can't find data myself (the ID)
