### ISSUE TITLE
请问所需的cookie是什么格式？

### ISSUE THREAD

**Issue by roogue** [genshin-kit/genshin-kit#4]
试了ltoken，也试了文档里`document.cookie`返回的结果

以上均出现`{ code: 10001, message: 'Please login' }`的错误

我是Asia地区的，也在`.loginWithCookie()`之前使用了`.setServerType("os")`

**Comment by Dragon-Fish** [comment]
@AlPha5130 猫猫，国际服，交给你了

**Comment by AlPha5130** [comment]
您好，请问您登录的网站是米游吗？

**Comment by Dragon-Fish** [comment]
> 您好，请问您登录的网站是米游社吗？

对，文档里好像忘记说了，国服与国际服需要的 cookie 不一样。

国服：米游社；国际服：hoyolab

**Comment by roogue** [comment]
> 您好，请问您登录的网站是米游社吗？

嗨，没听过米游社，`https://www.hoyolab.com/genshin/` 就文档里的这个网址。

而且文档里示例的 <App>.loginWithToken() 好像不起作用。

**Comment by Dragon-Fish** [comment]
> 而且文档里示例的 .loginWithToken() 好像不起作用。

草草草……`loginWithCookie(cookie: string)`，文档怕是写错了……

**Comment by Dragon-Fish** [comment]
因为是 ts 一般都是直接看 IDE 的代码提示，我就没仔细写文档（

**Comment by AlPha5130** [comment]
~~我好像没法复现问题~~

**Comment by AlPha5130** [comment]
Cookie 需要 `ltuid` 和 `ltoken` 两项

**Comment by roogue** [comment]
笑
> Cookie 需要 `ltuid` 和 `ltoken` 两项

![image](https://user-images.githubusercontent.com/57899698/119815068-bbc2e180-bf1d-11eb-9f30-0bede6d5c8de.png)
是类似这样的东西吗？

**Comment by Dragon-Fish** [comment]
```ts
import { GenshinKit } from 'genshin-kit'
const App = new GenshinKit()
App.loginWithCookie('ltoken=***; ltuid=***')
```

**Comment by roogue** [comment]
> ```ts
> import { GenshinKit } from 'genshin-kit'
> const App = new GenshinKit()
> App.loginWithCookie('ltoken=***; ltuid=***')
> ```

可了！万分感谢

**Comment by AlPha5130** [comment]
> 是类似这样的东西吗？
document.cookie 里应该有的吧
ltoken=<一大串>, ltuid=<数字>
