### ISSUE TITLE
[BUG] 关于国服 UID 200000000 的合法性验证

### ISSUE THREAD

**Issue by Android-KitKat** [genshin-kit/genshin-kit#46]
**选择您要汇报的包/Choose the package you want to report.**

- [x] @genshin-kit/core
- [ ] @genshin-kit/gacha

## 简述此故障/Describe the bug

在 188e4b1 中新增了支持 `2` 开头的 UID。

但是在验证国服 UID `200000000` 是否合法时，返回 `false`。

## 如何重现此故障/To Reproduce

直接使用 `node` 命令。

```js
const { isValidCnUid } = require('genshin-kit').util;

isValidCnUid(200000000);
isValidCnUid(200000001);
```

## 本应出现的情况/Expected behavior

验证国服 UID `200000000` 是否合法时，返回 `true`。

## 截图/Screenshots

![原神UID验证合法性](https://user-images.githubusercontent.com/6592315/134933671-3d1fc8c9-67f8-430a-b97c-3ea3de17faa9.png)

## 环境信息/Your environment

- 包版本/pkg version: 2.4.2
- Node.js: 14.15.0
- 系统/OS: Windows

## 额外说明/Additional context

国服确实存在这个玩家，图片来自 Womsxd/YuanShen_User_Info#22。

![原神UID200000000](https://user-images.githubusercontent.com/9006264/133719894-778921d7-ad55-408f-81fc-5f09d1fb23a0.png)

**Comment by AlPha5130** [comment]
已修复。
