### ISSUE TITLE
有什么方法能让python便利的调用代码呢？

### ISSUE THREAD

**Issue by KimigaiiWuyi** [genshin-kit/genshin-kit#5]
新手开发者在写hoshino bot的插件，准备利用这个完成一个原神bot查询uid信息的功能，正痛苦的看着api获取到的东西自己分离字段就发现了这个，但python好像不太能用这个kit~这是只支持js/ts吗？如果python想要调用js代码有什么便利的操作吗~

**Comment by undefined-moe** [comment]
推荐的解决方案：使用 [koishi](https://koishi.js.org) 框架。

**Comment by Dragon-Fish** [comment]
233 这是一个 Node.js 包啊，Python 当然无法使用啦。

如果是写原神 bot 推荐直接使用 [koishi](https://koishi.js.org/) 框架，因为我已经基于 genshin-kit 开发了一个原神插件，支持查询玩家角色等信息，开箱即用。（不如说 genshin-kit 就是从这个插件里解耦出来的）

如果你比较偏好 Python，那么你可能需要寻找合适的 Python 的“轮子”，或者阅读这个仓库的源代码使用 Python 进行重构，直接用 Python 调用 Node.js 可能有点阴间（

**Comment by Dragon-Fish** [comment]
如果你只是苦于猜想 API 返回的字段，也可以直接参考 [https://github.com/genshin-kit/genshin-kit/tree/master/src/types](https://github.com/genshin-kit/genshin-kit/tree/master/src/types) ，我已经帮你痛苦过了（
