### ISSUE TITLE
我收到一个错误无效请求

### ISSUE THREAD

**Issue by Nota30** [genshin-kit/genshin-kit#6]
```js
const { GenshinKit } = require('genshin-kit');
const App = new GenshinKit();
App.setServerType('os');
App.loginWithCookie('ltoken=token; ltuid=id');

App.getUserInfo(100000001).then(console.log, console.error);
```

我得到：
```
{ code: -10001, message: 'invalid request' }
```

**Comment by Dragon-Fish** [comment]
……你不能用海外服务器请求国服信息

**Comment by Nota30** [comment]
但我没有要求国家信息

**Comment by Dragon-Fish** [comment]
`App.setServerType('os')` 这里你设置了查询服务器为国际服

`App.getUserInfo(100000001)` 但这里查询的是一个天空岛账号

我也不知道你想干什么

**Comment by Nota30** [comment]
那是一个例子。我使用了另一个 uid

**Comment by Dragon-Fish** [comment]
https://github.com/genshin-kit/genshin-kit/commit/e3ca0abc21e240d92dc20565d1b2c947e3242987#diff-4b83f25e6a1cbd167860e6781726231bf8eb832be0bd41df14a5416643c86b1eL16-R16

@AlPha5130 我这里可能改错了什么东西，请问可以帮忙测试一下国际服的查询情况吗

**Comment by Nota30** [comment]
```js
App.getUserInfo(626744380).then(console.log, console.error);
```

**Comment by Dragon-Fish** [comment]
@Nota30 如果你有空的话可以帮忙配合调试一下吗：

进入 `node_modules/genshin-kit/lib/module/_getHttpHeaders.js` 这个文件，找到第19行 `'x-rpc-client_type': '5',`，将此处修改为 `'x-rpc-client_type': '4',`，然后再试一次

**Comment by Nota30** [comment]
好的

**Comment by Nota30** [comment]
它现在有效

**Comment by Dragon-Fish** [comment]
感谢您的配合，已确定这是我手癌导致的 BUG（

我已经部署了一个补丁，请更新您的依赖到 `^2.1.1` 版本。

确定不再出现此问题后您可以关闭这个 issue。如果遇到其他问题，欢迎再次提交 issue~

**Comment by Nota30** [comment]
谢谢

**Comment by AlPha5130** [comment]
疑似os查询修改了x-rpc_client_type的值和DS里的salt。
现已更新，等待下次发版测试。
