### ISSUE TITLE
请问这段代码是对的吗？

### ISSUE THREAD

**Issue by gorden0929** [genshin-kit/genshin-kit#7]
https://github.com/genshin-kit/genshin-kit/blob/0be6d97286d0b81f92e15784291683ea01cb7cdf/src/types/Character.ts#L6

请问这段代码是对的吗？我要更改name的数值可是他是number所以我改不了。

**Comment by Dragon-Fish** [comment]
这显然是不对的，应该是我犯手癌

PS. 你要不要~~水一个~~contrib

**Comment by AlPha5130** [comment]
Fixed in #9 .
